name: first workflow
on: [push]
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run:  echo "Helo World"
            - name: Multiline Commands
              run: |
               node -v   # node version
               npm -v    # npm version 
