name: first workflow
on: [push]
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run:  echo "Helo World"
            - name: Multiline Commands
              run: |
               node -v   # node version
               npm -v    # npm version 
    second-job:
      runs-on: ubuntu-latest
      steps:
        - name: fetch the code
          uses: actions/checkout@v3
        - name: echon a string
          run: echo "hello "
    

